version: '3.7'

services:
  core_insight:
    image: ${CORE_INSIGHT_DOCKER_IMAGE:?err}
    labels:
      org.hellarmate.service.title: "Core Insight API"
    restart: unless-stopped
    ports:
      - 127.0.0.1:${CORE_INSIGHT_PORT:?err}:${CORE_INSIGHT_PORT:?err}
    depends_on:
      - core
    volumes:
      - ${HELLARMATE_HOME_DIR:?err}/${CONFIG_NAME:?err}/core/insight/hellarcore-node.json:/insight/hellarcore-node.json
    profiles:
      - core
