[package]
name = "drive-proof-verifier"
version = "2.0.15"
edition = "2024"
rust-version = "1.73"

crate-type = ["cdylib"]

[features]
default = ["mocks", "json"]
mocks = ["dep:serde"]
json = ["dep:serde_json"]


[dependencies]

thiserror = { version = "1.0.39" }
hapi-grpc = { path = "../hapi-grpc" }
drive = { path = "../rs-drive", default-features = false, features = [
    "verify",
] }
hpp = { path = "../rs-hpp" }
tenderhellar-abci = { git = "https://github.com/hellarpay/rs-tenderhellar-abci" }
# tenderhellar-abci = { path = "../../../rs-tenderhellar-abci/abci" }
tracing = { version = "0.1.37" }
serde = { version = "1.0.171", default-features = false, optional = true }
serde_json = { version = "1.0.103", features = [
    "preserve_order",
], optional = true }
lazy_static = { version = "1.4.0" }
hex = { version = "0.4.3" }
