[package]

name = "hapi-grpc-macros"
version = "2.0.15"
edition = "2024"
description = "Macros used by hapi-grpc. Internal use only."

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.38"
heck = "0.4.1"

[dev-dependencies]

hapi-grpc = { path = "../hapi-grpc" }
