[package]
name = "platform-value-convertible"
authors = ["UraGun <hellarpay@hellar.io>"]
description = "Convertion to and from platform values"
version = "2.0.15"
edition = "2024"
rust-version = "1.73"
license = "MIT"
private = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = "2.0.15"
