site_name: Hellar Platform
plugins:
    - redirects:
        redirect_maps:
            'SDK/README.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-overview'
            'SDK/Overview.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-overview'
            'SDK/examples/fetch-an-identity-from-its-name.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-examples-fetch-an-identity-from-its-name'
            'SDK/examples/generate-a-new-mnemonic.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-examples-generate-a-new-mnemonic'
            'SDK/examples/pay-to-another-address.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-examples-paying-to-another-address'
            'SDK/examples/receive-money-and-check-balance.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-examples-receive-money-and-check-balance'
            'SDK/examples/sign-and-verify-messages.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-examples-sign-and-verify-messages'
            'SDK/examples/use-different-account.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-examples-use-different-account'
            'SDK/getting-started/about-schemas.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-getting-started-about-schemas'
            'SDK/getting-started/core-concepts.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-getting-started-core-concepts'
            'SDK/getting-started/hellar-platform-applications.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-getting-started-hellar-platform-applications'
            'SDK/getting-started/multiple-apps.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-getting-started-working-with-multiple-apps'
            'SDK/getting-started/quickstart.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-getting-started-quick-start'
            'SDK/getting-started/with-typescript.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-getting-started-with-typescript'
            'SDK/platform/about-platform.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-platform'
            'SDK/platform/contracts/about-contracts.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-contracts'
            'SDK/platform/contracts/create.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-contracts-create'
            'SDK/platform/contracts/get.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-contracts-get'
            'SDK/platform/contracts/publish.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-contracts-publish'
            'SDK/platform/contracts/update.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-contracts-update'
            'SDK/platform/documents/about-documents.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-documents'
            'SDK/platform/documents/broadcast.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-documents-broadcast'
            'SDK/platform/documents/create.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-documents-create'
            'SDK/platform/documents/get.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-documents-get'
            'SDK/platform/identities/about-identity.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-identities'
            'SDK/platform/identities/get.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-identities-get'
            'SDK/platform/identities/register.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-identities-register'
            'SDK/platform/identities/topUp.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-identities-topup'
            'SDK/platform/names/about-hpns.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-names'
            'SDK/platform/names/register.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-names-register'
            'SDK/platform/names/resolve.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-names-resolve'
            'SDK/platform/names/resolveByRecord.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-names-resolvebyrecord'
            'SDK/platform/names/search.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-names-search'
            'SDK/usage/hapi.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-usage-hapi'
            'SDK/usage/hellarcorelib-primitives.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-usage-hellarcore-lib-primitives'
            'SDK/wallet/about-wallet-lib.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-wallet'
            'SDK/wallet/accounts.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-wallet-accounts'
            'SDK/wallet/signing-encrypt.md': 'https://hellarplatform.readme.io/docs/hellar-sdk-wallet-signing-encrypt'
