[package]
name = "platform-versioning"
authors = ["UraGun <hellarpay@hellar.io>"]
description = "Version derivation"
version = "2.0.15"
edition = "2024"
rust-version = "1.73"
license = "MIT"
private = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = "2.0.15"
