[package]
name = "hapi-grpc"
description = "GRPC client for Hellar Platform"
version = "2.0.15"
authors = [
    "UraGun <hellarpay@hellar.io>",
    "Igor Markin <igor.markin@hellar.io>",
    "Łukasz Klimek <lukasz.klimek@hellar.io>",
    "Anton Suprunchuk <anton.suprunchuk@hellar.io>",
    "Ivan Shumkov <shumkov@hellar.io>",
]
edition = "2021"
rust-version = "1.73"
license = "MIT"

[features]
default = ["core", "platform", "client", "serde"]
core = []
platform = []
# Re-export Hellar Platform protobuf types as `hapi_grpc::platform::proto`
tenderhellar-proto = []
client = ["tonic/channel", "tonic/tls", "tonic/tls-roots", "platform"]
serde = ["dep:serde", "dep:serde_bytes"]

[dependencies]
prost = { version = "0.11.9" }
tonic = { version = "0.9.2", features = [
    "codegen",
    "prost",
], default-features = false }
serde = { version = "1.0.171", optional = true, features = ["derive"] }
serde_bytes = { version = "0.11.12", optional = true }
tenderhellar-proto = { git = "https://github.com/hellarpay/rs-tenderhellar-abci" }
hapi-grpc-macros = { path = "../rs-hapi-grpc-macros" }
platform-version = { path = "../rs-platform-version" }

[build-dependencies]
tonic-build = { version = "0.9.2" }

[lib]

[[example]]
name = "core_example"
path = "clients/core/v0/rust/core_example.rs"


[[example]]
name = "platform_example"
path = "clients/platform/v0/rust/platform_example.rs"

[package.metadata.cargo-machete]
ignored = ["platform-version", "serde_bytes"]
